name: Build FE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - name: Use Node.js 30.x
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm install

  trigger-be:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Trigger BUILD-BE Workflow
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.TRIGGER_PAT }}" \
            -H "Accept: application/vnd.github.everest-preview+json" \
            https://api.github.com/repos/dimosoftuni/Library-Catalog-be/dispatches \
            -d '{"event_type": "trigger-build-be"}'
